### ISSUE TITLE
Add SNI field when manually inputting a server

### ISSUE THREAD

**Issue by iamtrazy** [netchx/netch#643]
### Describe the feature you want

when use add [vless] server option it doesn't provide a method to input SNI . the Host field doesnt give the function properly. so please add a SNI field to server input panel.

**Comment by ghost** [comment]
Custom configuration files will be supported

**Comment by testermania** [comment]
mode (3) bypass lan grpc support doesn't  work. v2rayng v2rayn working good with same server (cdn grpc).
maybe sni and service name setting is needed.


server xray config.json
`{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 2002,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "44f234ef-82e4-4162-9842-69aa375525f5" // 填写你的 UUID
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "grpc",
        "grpcSettings": {
          "serviceName": "mydomain.com" // 填写你的 ServiceName
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}`


`Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 windows/amd64)
A unified platform for anti-censorship.
2021/06/30 11:28:07 [Info] infra/conf/serial: Reading config: ..\data\last.json
2021/06/30 11:28:07 [Warning] core: Xray 1.4.2 started
2021/06/30 11:28:17 [Warning] [2930530796] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:17 [Warning] [1409600338] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:17 [Warning] [4149458431] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [954579742] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [1252409957] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [3263566941] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [1830318961] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [1670146538] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [303596412] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [2068844434] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [3110458756] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [1115112384] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [2674411162] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:20 [Warning] [2380843839] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed`

e3b1ae0 update

![grpc](https://user-images.githubusercontent.com/61498468/124566668-f0df1f80-de4b-11eb-8a45-b72dc076a05a.PNG)


data/settings.json (last.json this file doesnt exist)

[settings.zip](https://github.com/netchx/netch/files/6769254/settings.zip)

v2rayN working settings
path = serviceName
camouflage domain and sni, must be the same as the main domain in cdn (if I use address cdn ip instead of domain)

![v2rayn](https://user-images.githubusercontent.com/61498468/124599960-e97d3d80-de6e-11eb-84fe-8720d11d5b9d.PNG)

update  6407172

it only works with cdn ip. not working with domain name. host doesn't matter, it's empty or running with a different domain name.
![grpc](https://user-images.githubusercontent.com/61498468/124900591-e490c900-dfe9-11eb-8fd1-6c41c7f87cc0.PNG)

**Comment by testermania** [comment]
![grpc](https://user-images.githubusercontent.com/61498468/124566668-f0df1f80-de4b-11eb-8a45-b72dc076a05a.PNG)

**Comment by chsbuffer** [comment]
@testermania also comment Netch generated xray-core client config (data\last.json) please
