### ISSUE TITLE
Freezing and lagging and blue screen issues

### ISSUE THREAD

**Issue by MalinrRuwan** [netchx/netch#690]
When started the it freezes the whole environment and at last it restarts after a blue screen.

**Comment by netch-org** [comment]
Show your blue screen code

**Comment by MalinrRuwan** [comment]
Ks.sys
SYSTEM_SERVICE_EXCEPTION

**Comment by DraganzN** [comment]
I have some bluescreen, lagging issues.
What I have done is,
1) Uninstall NF Service
2) Remove Netch Firewall Rules from Options.
![Screenshot 2021-07-07 080938](https://user-images.githubusercontent.com/14966649/124692183-b97b7c00-defa-11eb-993f-db74a8841e9f.png)

Then I have never faced any issue. It was fixed by doing the above steps.

My Bluescreen error was: DPC_WATCHDOG_VIOLATION
My OS: Windows 10 21H1

**Comment by MalinrRuwan** [comment]
If we removeand uninstall that it will not forward the traffic

**Comment by MalinrRuwan** [comment]
Okay. Thanks

**Comment by MalinrRuwan** [comment]
Still the issue is continuing in my pc and a friend of mine please help me to fix this.

**Comment by DraganzN** [comment]
There's no fix or issue. Try using other apps. If it works for you, then problem solved.

**Comment by MalinrRuwan** [comment]
How to rollback that again what is open/close state

**Comment by netch-org** [comment]
We don't have any driver called ks.sys

According to the current error code, it is your problem

We recommend that you reinstall a clean system
